version: 2
notify:
 webhooks:
   - url: https://claraio-circledisc.herokuapp.com/hooks/circleci
jobs:
  build:
    docker:
      - image: chinodesuuu/ci-amethyst:latest  
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.05.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build Monika (Ubuntu)
          command: docker build -t chinodesuuu/monika:ubuntu ./Monika-Ubuntu
      - run:
          name: Build Sayori (Ubuntu)
          command: docker build -t chinodesuuu/sayori:ubuntu ./Sayori-Ubuntu
  deploy:
    docker:
      - image: chinodesuuu/ci-amethyst:latest
    steps:
      -setup_remote_docker
          name: Install Docker client
          command: |
            set -x
            VER="17.05.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin      
      - run:
          name: Docker Push (Monika)
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS && docker push chinodesuuu/monika:ubuntu
      - run:
          name: Docker Push (Sayori)
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS && docker push chinodesuuu/sayori:ubuntu          
          

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 4* * 0"
          filters:
            branches:
              only: master

    jobs:
      - build
         context: org-global
      - deploy
         requires:
            - build
         context: org-global
  