version: 2
notify:
  webhooks:
    - url: https://circledisc-clarity.herokuapp.com/webhook/circle
jobs:
  build:
    docker:
      - image: chinodesuuu/ci-amethyst:latest  
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.05.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build Monika Gateway (Alpine)
          command: docker build -t claritymoe/monika:alpine ./Monika-Alpine          
      - run:
          name: Build Sayori (Ubuntu)
          command: docker build -t claritymoe/sayori:ubuntu ./Sayori-Ubuntu
  deploy:
    docker:
      - image: chinodesuuu/ci-amethyst:latest
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.05.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build Monika (Alpine)
          command: docker build -t claritymoe/monika:alpine -t claritymoe/monika:latest ./Monika-Alpine
      - run:
          name: Build Monika (Ubuntu)
          command: docker build -t claritymoe/monika:ubuntu ./Monika-Ubuntu
      - run:
          name: Build Sayori (Ubuntu)
          command: docker build -t claritymoe/sayori:ubuntu ./Sayori-Ubuntu          
      - run:
          name: Docker Push (Sayori Ubuntu)
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS && docker push claritymoe/sayori:ubuntu
      - run:
          name: Docker Push (Monika Alpine)
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS && docker push claritymoe/monika:alpine && docker push claritymoe/monika:latest
workflows:
  version: 2
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only: master
    jobs:
      - deploy
  build-n-deploy: 
    jobs:
      - build
      - deploy:
          requires:
             - build